name: eastmeetswest
favicon: null
layout_spectrum: 0.26362
typography_spectrum: 0.3059563459828496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15100c'
    - '#828a8c'
    - '#afbec1'
    - '#d5372c'
  brandStrength: 1
  lightness: 0.18885587621480227
  saturation: 0.9720754104200751
  rhythmicContrast: 0.5261707627214491
purpose: []
