name: eastmeetswest
favicon: null
layout_spectrum: 0.6908216455485672
typography_spectrum: 0.3059563459828496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8896930271293968
  lightness: 0.18885587621480227
  saturation: 0.9720754104200751
  rhythmicContrast: 0.5261707627214491
purpose: []
